version: '3.8'

x-common-variables: &common-variables
  MONGO_DATABASE: coins
  MONGO_USER: user
  MONGO_PASSWORD: pass
  MONGO_URI: mongodb+srv://<user>:<pass>@cluster0.jkmb2.mongodb.net/coins?retryWrites=true&w=majority
  NODE_ENV: production
  APIKEY: <api-key>

services:
  mongo_db:
    image: mongo
    container_name: mongodb
    environment:
      <<: *common-variables
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    restart: always

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mongo_db
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    environment:
      <<: *common-variables
      
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000